### ISSUE TITLE
Disable location permission

### ISSUE THREAD

**Issue by AhmedNourJamalElDin** [Kommunicate-io/Kommunicate-Android-Chat-SDK#177]
Hello,

I have integrated Kommunicate in my app, but when publishing the application, I got an error:

> You have declared that your app targets under 13 age groups, but your app asks for location permissions.: b'{\n "error": {\n "code": 403,\n "message": "You have declared that your app targets under 13 age groups, but your app asks for location permissions.",\n "status": "PERMISSION_DENIED"\n }\n}\n'
 
My app is for kids, and I want to integrate Kommunicate so I can reach the parents easily.

BTW I'm using Flutter plugin where it uses this sdk and iOS SDK as I know.

Any idea to resolve this, please?

**Comment by reytum** [comment]
@AhmedNourJamalElDin You can disable the location setting as mentioned here: https://docs.kommunicate.io/docs/flutter-customization#hidingshowing-media-attachment-and-location-sharing-options

Then remove the permissions from your AndroidManifest.xml file by adding the below entries inside the <manifest tag:

```
  <uses-permission
        android:name="android.permission.ACCESS_COARSE_LOCATION"
        tools:node="remove" />
    <uses-permission
        android:name="android.permission.ACCESS_FINE_LOCATION"
        tools:node="remove" />
```
Add the tools import at the top of the file(within manifest declaration):
```
xmlns:tools="http://schemas.android.com/tools"
```
Check this for reference: https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/blob/23360ae6ac68de4ce9c1a46644be6cbd64d43894/kommunicate/src/main/AndroidManifest.xml#L2

**Comment by AhmedNourJamalElDin** [comment]
Thanks a lot, I will try this.
