### ISSUE TITLE
How to set parent activity for conversation activity?

### ISSUE THREAD

**Issue by rohit-personatech** [Kommunicate-io/Kommunicate-Android-Chat-SDK#180]
How to set the parent activity to the conversation activity so that the user navigates back to the parent activity when the conversation activity is launched from chat notification.

`ApplozicSetting.getInstance(getContext()).setParentActivity("<COMPLETE-RESOLVED-PATH-OF-THE-ACTIVITY>");`

^ found this from documentation but seems like ApplozicSetting is no longer available in `io.kommunicate.sdk:kommunicateui:2.1.4` package.

Do let me know if there is any other way to set parent activity.

**Comment by reytum** [comment]
@rohit-personatech 
Use KommunicateSetting instead:
```
KommunicateSetting.getInstance(getContext()).setParentActivity("<COMPLETE-RESOLVED-PATH-OF-THE-ACTIVITY>");
```

**Comment by rohit-personatech** [comment]
@reytum thanks. this fixes my problem.

It'll be great if you update the docs with same thing.
