### ISSUE TITLE
Meta data's parameters are not received on server side 

### ISSUE THREAD

**Issue by attriaman2520** [Kommunicate-io/Kommunicate-Android-Chat-SDK#197]
**When i send a message i send a parameter in metadata. Here is log which get printed when i send a message :**

Sending message to server: {
      "applicationId": "174afd6c613bbb5be0bbd725cafbe88",
      "attDownloadInProgress": false,
      "canceled": false,
      "clientGroupId": "info@usa2georgia.com_523659",
      "connected": false,
      "contactIds": "",
      "contentType": 0,
      "createdAtTime": 1618817104202,
      "delivered": false,
      "deviceKey": "235cc17d-d712-4ad2-97d5-d4bc29753274",
      "groupId": 57925473,
      "hidden": false,
      "key": "212a5201-f473-4f05-9322-925342e92380",
      "message": "hello. testing again",
      **"metadata": {
        "userId": "66b3d32cd58a51a54d35a3547cc7e5e0"
      },**
      "read": true,
      "replyMessage": 0,
      "sendToDevice": false,
      "sent": true,
      "sentMessageTimeAtServer": 0,
      "sentToServer": true,
      "shared": false,
      "source": 2,
      "status": 1,
      "storeOnDevice": true,
      "type": 5,
      "userKey": "974bb53b-3768-43f0-9cc0-24f5e9a6fc9e"
    }

**But our web guy is unable to get "userId" under metadata on his side. Here is the request he is getting using **"dialogflow"**. Can you help us with this?**

{"responseId":"55eb9d3d-1311-4c7d-8c65-e9271be3a59c-d74139ee","queryResult":{"queryText":"u10d2u10d0u10dbu10d0u10e0u10efu10ddu10d1u10d0","parameters":[],"allRequiredParamsPresent":true,"fulfillmentMessages":[{"payload":{"metadata":{"payload":[{"message":"u10d8u10dcu10e4u10ddu10e0u10dbu10d0u10eau10d8u10d0 u10d0u10dbu10d0u10dcu10d0u10d7u10d8u10e1 u10e8u10d4u10e1u10d0u10eeu10d4u10d1","title":"u10d8u10dcu10e4u10ddu10e0u10dbu10d0u10eau10d8u10d0 u10d0u10dbu10d0u10dcu10d0u10d7u10d8u10e1 u10e8u10d4u10e1u10d0u10eeu10d4u10d1"},{"message":"u10d6u10ddu10d2u10d0u10d3u10d8 u10d8u10dcu10e4u10ddu10e0u10dbu10d0u10eau10d8u10d0","title":"u10d6u10ddu10d2u10d0u10d3u10d8 u10d8u10dcu10e4u10ddu10e0u10dbu10d0u10eau10d8u10d0"}],"contentType":"300","templateId":"6"},"message":"u10dbu10ddu10d2u10d4u10e1u10d0u10dau10dbu10d4u10d1u10d8 $firstname, u10dbu10d4 USA2GEORGIA-u10e1 u10d1u10ddu10e2u10d8 u10d5u10d0u10e0. u10d8u10dcu10e4u10ddu10e0u10dbu10d0u10eau10d8u10d8u10e1 u10dbu10d8u10e1u10d0u10e6u10d4u10d1u10d0u10d3, u10d2u10d7u10eeu10ddu10d5u10d7, u10d0u10d8u10e0u10e9u10d8u10ddu10d7:","platform":"kommunicate"}}],"outputContexts":[{"name":"projects/usa2bot-emqd/agent/sessions/57925473/contexts/actions-followup","lifespanCount":2},{"name":"projects/usa2bot-emqd/agent/sessions/57925473/contexts/__system_counters__","lifespanCount":1,"parameters":{"no-input":0,"no-match":0}}],"intent":{"name":"projects/usa2bot-emqd/agent/intents/3bf1bb94-7000-4122-a3fc-78efcee19f63","displayName":"actions"},"intentDetectionConfidence":1,"languageCode":"en"},"originalDetectIntentRequest":{"payload":{"messageSource":"2","botId":"usa2georgia-bot-ahpos","attachments":[],"groupId":"57925473","applicationId":"174afd6c613bbb5be0bbd725cafbe88"}},"session":"projects/usa2bot-emqd/agent/sessions/57925473"}
white_check_mark
eyes
raised_hands

**Comment by devashishmamgain** [comment]
we will check if there is any issue with sending message metadata to Dialogflow.

In the mean time, if you are using it for userId, please try this approach https://docs.kommunicate.io/docs/bot-dialogflow-integration#pass-custom-data-to-bot-platform
As userId will belong to a conversation, so passing it in chat context will be better

**Comment by attriaman2520** [comment]
Devash did you check  on your end that Metadata pass from Andriod app to Dialogflow? I also tried Kommunicate.updateChatContext(activity,messageMetaData) it did not work. also this method is deprecated now.

**Comment by reytum** [comment]
@attriaman2520 The method is deprecated but should still work. The new method is a below:
```java
 KmSettings.updateChatContext(context, metadata);
```
Also, this will only work after KmConversationBuilder or Login success. You can update the chat context in onSuccess callback of the method you are using.

The chat context however needs to be sent under KM_CHAT_CONTEXT key in the metadata. Use the below code:

```java
Map<String, Object> mChatContext = new HashMap();
//Add some data to the chat context

Map<String, String> messageMetadata = new HashMap();
messageMetadata.put(KmSettings.KM_CHAT_CONTEXT, GsonUtils.getJsonFromObject(mChatContext, Map.class));

KmSettings.updateChatContext(context, messageMetadata);
```

We will update the docs for the same.

**Comment by reytum** [comment]
@attriaman2520 
Use the new method as below:

```java
       Map<String, String> stringStringMap = new HashMap<>();
        stringStringMap.put("Key", "Value");
        KmSettings.updateChatContext(this, stringStringMap);
```

**Comment by attriaman2520** [comment]
Thanks @reytum . It worked in case of Android. We could not find this method incase of IOS. Could you help with that?

**Comment by Samir1810** [comment]
Hi, Please try this one https://docs.kommunicate.io/docs/ios-customization#pass-custom-data-to-bot-platform

**Comment by attriaman2520** [comment]
@Samir1810  thanks that worked

**Comment by attriaman2520** [comment]
@Samir1810  Could you tell how to enable delete conversation in iOS?

**Comment by Samir1810** [comment]
@attriaman2520 Are you looking to delete the user chat widget end conversation or the dashboard?
