### ISSUE TITLE
Wrong storage permission request on API version 10+ 

### ISSUE THREAD

**Issue by HungryCup** [Kommunicate-io/Kommunicate-Android-Chat-SDK#212]
Permission WRITE_EXTERNAL_STORAGE will no longer provide write access when targeting Android 10 and above. Details: https://developer.android.com/training/data-storage/shared/media#request-permissions

But in your SDK, WRITE_EXTERNAL_STORAGE is requested regardless of the API version.

Client can set attribute android:maxSdkVersion on that permission in manifest, it has the effect of removing <uses-permission> element on higher Android SDK versions, at least in terms of how runtime permissions work. 

```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
                 android:maxSdkVersion="28" />
```

There is a lint warning in AS with regards to WRITE_EXTERNAL_STORAGE, it suggest set atrribute android:maxSdkVersion="28". But in that case verification that both WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE permissions granted will always not pass (ConversationActivity.java:700). The files selection screen will not open and will show up snackbar "Storage permission is required...".

**Comment by rikapsu2018** [comment]
I am getting same issue

**Comment by amntoppo** [comment]
Will be fixed in the next release.

**Comment by rikapsu2018** [comment]
This is still not working. Same on v2.2.2

**Comment by amntoppo** [comment]
@rikapsu2018 What is your Android SDK version? 
We tested from our side and it was working fine in the new version.

**Comment by rikapsu2018** [comment]
@amntoppo 
SDK version: 30

**Comment by rikapsu2018** [comment]
@amntoppo Any additional code is needed before open the chatbot?

**Comment by amntoppo** [comment]
@rikapsu2018 You have to use `implementation 'io.kommunicate.sdk:kommunicateui:2.2.2'` in your build.gradle

**Comment by rikapsu2018** [comment]
Of course, I used it. v2.2.2 @amntoppo

**Comment by amntoppo** [comment]
No additional code required from your side. We have tested from our side and it works fine in the new version.
Have you tried to remove the app completely before installing ?
Also, is it working on your Android Agent app?

**Comment by rikapsu2018** [comment]
Uninstalled & tried: same result.

**Comment by amntoppo** [comment]
Are you granting any storage permission from your App? If you are, can I have a look?

**Comment by rikapsu2018** [comment]
@amntoppo Sorry, it works. I updated my manifest

**Comment by amntoppo** [comment]
No problem. It's good that it was resolved.
