### ISSUE TITLE
Android 12 Support

### ISSUE THREAD

**Issue by igusef** [Kommunicate-io/Kommunicate-Android-Chat-SDK#245]
When are you going to support Android SDK API 31?

**Comment by Kommunicate-chat** [comment]
-- Please reply above this line --


            HI there,

We would like to inform you that it will be added in our next release.
***@***.***
How would you rate my reply?
Great [1]    Okay [2]    Not Good [3]

--
Kommunicate Support
***@***.***


Links:
------
[1]
https://secure.helpscout.net/satisfaction/480517475/record/5055768795/1/
[2]
https://secure.helpscout.net/satisfaction/480517475/record/5055768795/2/
[3]
https://secure.helpscout.net/satisfaction/480517475/record/5055768795/3/
