### ISSUE TITLE
enter_message_hint is never used

### ISSUE THREAD

**Issue by RemiSan** [Kommunicate-io/Kommunicate-Android-Chat-SDK#268]
Hello,

I am integrating the Kommunicate Flutter SDK and I'm currently having a problem with the localization on the Android side. I'm successfully translating most of the resources to French and it seems to me that we are not able to use a customized string for the hint "Write a Message.." used at the bottom of this screen.

![Screenshot_20220420-111822](https://user-images.githubusercontent.com/48949177/164267031-bc45c71a-1fcd-406e-a552-2918c3032238.png)

The string resource that seems to mean to be edited is `enter_message_hint` in [mobicom_strings.xml](https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/blob/master/kommunicateui/src/main/res/values/mobicom_strings.xml) but it is never used.

I think that this part of the code is the problem :

```java
messageEditText.setHint(!TextUtils.isEmpty(alCustomizationSettings.getEditTextHintText()) ? alCustomizationSettings.getEditTextHintText() : getString(R.string.enter_message_hint));
``` 

as `alCustomizationSettings.getEditTextHintText()` is never Empty and contains "Write a Message.."

**Comment by amntoppo** [comment]
Hello, 
Please follow these steps to change the editText Hint text in Android:
https://docs.kommunicate.io/docs/flutter-customization#android

In applozic-settings.json, there exists a "editTextHintText". Change it's value to your desired language and you should be able to do it.

**Comment by Sathyan-Elangovan** [comment]
Hi @RemiSan Can you confirm whether the given solution is worked or not?

**Comment by RemiSan** [comment]
Hi, I just tested using the file @amntoppo mentioned and it worked, I put an empty string for `editTextHintText` in `applozic-settings.json` so that 
```java 
TextUtils.isEmpty(alCustomizationSettings.getEditTextHintText())
``` 
was true and it uses 
```java 
getString(R.string.enter_message_hint)
```
I couldn't just "change the value to your desired language" in `applozic-settings.json` as you recommended because it would just use one value, but I need it to change depending on the device language.
I feel like it's kind of a "hack", I don't know if it was intended to be used that way but still, it works. Thanks :)

**Comment by amntoppo** [comment]
Thanks for pointing out the issue, @RemiSan 
We have added a fix for this. Now you will be able to set the hint text from both applozic-settings.json and localizable strings, whichever fits your requirement.
