### ISSUE TITLE
Regarding Custom View for Registering the user to kommunicate 

### ISSUE THREAD

**Issue by venugopal2412** [Kommunicate-io/Kommunicate-Android-Chat-SDK#293]
I need to set the email and password without opening the sdk support views for getting the details from user for registration purpose is there any possibilities

**Comment by amntoppo** [comment]
Yes, you can use the Kommunicate.login() method and pass your customer's userid, email and password.
You can follow the documentation of the same:
https://docs.kommunicate.io/docs/android-authentication#3-registered-user

**Comment by venugopal2412** [comment]
Thanks for the support
