### ISSUE TITLE
Image problem on Android 10 OS

### ISSUE THREAD

**Issue by banicrock** [Kommunicate-io/Kommunicate-Android-Chat-SDK#76]
Showing image and play sound doesn't work on Android OS 10 (permissions are active).
It is easy to reproduce on real device as well on Emulator.

**Comment by reytum** [comment]
@banicrock We are working on Android 10 support on priority. Will let you know once we release this.

**Comment by svenmonesrc** [comment]
hi @reytum & @devashishmamgain. Is there an update on this issue? We plan to roll out our app including kommunicate SDK within the next 3 weeks. But this issue blocks the roll out... Thanx in advance for any info about this issue.

**Comment by reytum** [comment]
@svenmonesrc We will be releasing this fix by next week.

**Comment by svenmonesrc** [comment]
@reytum : thanx, real fast and "good to here" update :)

**Comment by reytum** [comment]
@svenmonesrc The update is out. You can update to version 1.9.6.
